print("Hello World!")
# Print outputs string (text inside "")
print("   /|")
print("  / |")
print(" /  |")
print("/___|")
# Code executes each line from top to bottom
print("|------|")
print("|      |")
print("|      |")
print("|------|")
print("This is a box!")
print(6/2)
